### ISSUE TITLE
Fix Config.tryGet to parse lists

### ISSUE THREAD

**Issue by PxlBuzzard** [Circular-Studios/Dash#118]
In YAML-land the following snippet is legal, but Config.tryGet breaks when attempting to read either of the nodes.

``` yaml
men: [John Smith, Bill Jones]
women:
  - Mary Smith
  - Susan Williams
```
