### ISSUE TITLE
[Animation] Define animations from YAML

### ISSUE THREAD

**Issue by PxlBuzzard** [Circular-Studios/Dash#174]
We need some way to define animations in yaml. I don't know what form that will take yet, but I have a suggestion of how it might be done:

``` yaml

---
Name: Foo
Script:
    ClassName: foo.bar
Mesh: foo
Material: bar
Animations:
    Idle: foo_idle
    Run: foo_run
```
