### ISSUE TITLE
Implement "Tweakable" Attribute

### ISSUE THREAD

**Issue by wozniakty** [Circular-Studios/Dash#26]
``` d
@Tweakable int posX;
```

``` yaml
object1:
    script:
        className: "/a/script.d"
        posX: 5
```
