### ISSUE TITLE
Implement Child Creation in Yaml

### ISSUE THREAD

**Issue by wozniakty** [Circular-Studios/Dash#83]
Highest priority would be anonymous child creation, where a new object could just be defined in the standard yaml format in a Children attribute.
Additionally, designating objects by name in Children attribute would be ideal

Example:

``` yml
Name: ExampleObject
Transform:
    Position: !Vector3 1 1 1
Children:
    -
        Name: ExampleChild
        Light: !Light-Ambient
            Color: !Vector3 1 1 1
    - OtherChild
```
